//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalInformationSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HospitalInformationSystem.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje nove.
        /// </summary>
        internal static string AddEquipment {
            get {
                return ResourceManager.GetString("AddEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodavanje nove.
        /// </summary>
        internal static string AddEquipmentEdit {
            get {
                return ResourceManager.GetString("AddEquipmentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodavanje nove.
        /// </summary>
        internal static string AddEquipmentLC {
            get {
                return ResourceManager.GetString("AddEquipmentLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dopuna odabrane.
        /// </summary>
        internal static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje novog.
        /// </summary>
        internal static string AddMedicine {
            get {
                return ResourceManager.GetString("AddMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novu.
        /// </summary>
        internal static string AddRoom {
            get {
                return ResourceManager.GetString("AddRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMENI.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraživač.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IZMENI.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena leka.
        /// </summary>
        internal static string ChangeMedicineTitle {
            get {
                return ResourceManager.GetString("ChangeMedicineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena prostorije.
        /// </summary>
        internal static string ChangeRoomTitle {
            get {
                return ResourceManager.GetString("ChangeRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izađi.
        /// </summary>
        internal static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POTVRDI.
        /// </summary>
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trenutni zamenski:.
        /// </summary>
        internal static string CurrentRepacement {
            get {
                return ResourceManager.GetString("CurrentRepacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje postojeće.
        /// </summary>
        internal static string DeleteEquipment {
            get {
                return ResourceManager.GetString("DeleteEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uklanjanje odabrane.
        /// </summary>
        internal static string DeleteEquipmentLC {
            get {
                return ResourceManager.GetString("DeleteEquipmentLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje postojećeg.
        /// </summary>
        internal static string DeleteMedicine {
            get {
                return ResourceManager.GetString("DeleteMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje postojeće.
        /// </summary>
        internal static string DeleteRoom {
            get {
                return ResourceManager.GetString("DeleteRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis namene:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljan prikaz.
        /// </summary>
        internal static string DetailView {
            get {
                return ResourceManager.GetString("DetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinamička oprema:.
        /// </summary>
        internal static string DynamicEquipment {
            get {
                return ResourceManager.GetString("DynamicEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena postojeće.
        /// </summary>
        internal static string EditEquipment {
            get {
                return ResourceManager.GetString("EditEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena opreme.
        /// </summary>
        internal static string EditEquipmentTitle {
            get {
                return ResourceManager.GetString("EditEquipmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena postojećeg.
        /// </summary>
        internal static string EditMedicine {
            get {
                return ResourceManager.GetString("EditMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena postojeće.
        /// </summary>
        internal static string EditRoom {
            get {
                return ResourceManager.GetString("EditRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPREMA.
        /// </summary>
        internal static string EquipmentTitle {
            get {
                return ResourceManager.GetString("EquipmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajl.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprat:.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprat.
        /// </summary>
        internal static string FloorInTable {
            get {
                return ResourceManager.GetString("FloorInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opšti prikaz.
        /// </summary>
        internal static string GeneralView {
            get {
                return ResourceManager.GetString("GeneralView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra:.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        internal static string IdInTable {
            get {
                return ResourceManager.GetString("IdInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSNOVNE INFORMACIJE.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sastojci:.
        /// </summary>
        internal static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u magacinu.
        /// </summary>
        internal static string InMagacine {
            get {
                return ResourceManager.GetString("InMagacine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija:.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string LocationInTable {
            get {
                return ResourceManager.GetString("LocationInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glavni prozor.
        /// </summary>
        internal static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentari lekara.
        /// </summary>
        internal static string MedicineComments {
            get {
                return ResourceManager.GetString("MedicineComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekovi.
        /// </summary>
        internal static string Medicines {
            get {
                return ResourceManager.GetString("Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno stanje:.
        /// </summary>
        internal static string MinState {
            get {
                return ResourceManager.GetString("MinState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakazivanje premeštanje.
        /// </summary>
        internal static string MoveSheduliing {
            get {
                return ResourceManager.GetString("MoveSheduliing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string NameInTable {
            get {
                return ResourceManager.GetString("NameInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv zemnskog leka.
        /// </summary>
        internal static string NameOfReplacementInTable {
            get {
                return ResourceManager.GetString("NameOfReplacementInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizacija.
        /// </summary>
        internal static string Personalization {
            get {
                return ResourceManager.GetString("Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina:.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina.
        /// </summary>
        internal static string QuantityInTable {
            get {
                return ResourceManager.GetString("QuantityInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brisanje postojeće.
        /// </summary>
        internal static string RemoveEquipmentEdit {
            get {
                return ResourceManager.GetString("RemoveEquipmentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renoviranje.
        /// </summary>
        internal static string Renovation {
            get {
                return ResourceManager.GetString("Renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamenski lek:.
        /// </summary>
        internal static string ReplacementMedicine {
            get {
                return ResourceManager.GetString("ReplacementMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj izveštaj.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostorije.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        internal static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanje u magacinu:.
        /// </summary>
        internal static string StateInMagacine {
            get {
                return ResourceManager.GetString("StateInMagacine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statička oprema:.
        /// </summary>
        internal static string StaticEquipment {
            get {
                return ResourceManager.GetString("StaticEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupna količina.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        internal static string TypeInTable {
            get {
                return ResourceManager.GetString("TypeInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Način upotrebe:.
        /// </summary>
        internal static string WayOfUse {
            get {
                return ResourceManager.GetString("WayOfUse", resourceCulture);
            }
        }
    }
}
